"""Default YouTube channels and topic definitions."""

from __future__ import annotations

DEFAULT_CHANNELS = [
    {"label": "Bloomberg Television", "handle": "@BloombergTelevision"},
    {"label": "CNBC Television", "handle": "@CNBCTelevision"},
    {"label": "Reuters", "handle": "@Reuters"},
    {"label": "Yahoo Finance", "handle": "@YahooFinance"},
    {"label": "Financial Times", "handle": "@FinancialTimes"},
]

DEFAULT_TRANSCRIPT_LANGUAGES = ["en", "en-US", "en-GB"]

TOPIC_KEYWORDS = {
    "Inflation & Rates": [
        "inflation",
        "interest rate",
        "interest rates",
        "fed",
        "federal reserve",
        "central bank",
        "bank of england",
        "bank of japan",
        "ecb",
        "cpi",
        "monetary policy",
    ],
    "Growth & Recession": [
        "economy",
        "economic",
        "gdp",
        "growth",
        "recession",
        "slowdown",
        "expansion",
        "outlook",
        "productivity",
    ],
    "Labor & Consumers": [
        "jobs",
        "employment",
        "unemployment",
        "wages",
        "consumer",
        "retail",
        "housing",
        "spending",
        "household",
        "debt",
    ],
    "Trade & Policy": [
        "trade",
        "tariff",
        "tariffs",
        "exports",
        "imports",
        "sanctions",
        "budget",
        "tax",
        "fiscal",
        "policy",
    ],
    "Markets & Commodities": [
        "stocks",
        "shares",
        "bond",
        "bonds",
        "yield",
        "yields",
        "oil",
        "gas",
        "gold",
        "commodities",
        "commodity",
        "currency",
        "dollar",
    ],
    "Geopolitics & Supply": [
        "shipping",
        "supply chain",
        "middle east",
        "china",
        "europe",
        "conflict",
        "war",
        "opec",
        "red sea",
        "strait of hormuz",
    ],
}

HEADLINE_KEYWORDS = {
    keyword
    for keywords in TOPIC_KEYWORDS.values()
    for keyword in keywords
}

PROMO_PHRASES = {
    "thanks for watching",
    "thanks for joining us",
    "welcome back",
    "hit the like button",
    "subscribe to our channel",
    "download our app",
    "turn on notifications",
    "stick around",
}

NOISE_SNIPPETS = {
    "[music]",
    "[applause]",
    "[laughter]",
    "[__]",
}

STOPWORDS = {
    "a",
    "about",
    "after",
    "all",
    "also",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "been",
    "but",
    "by",
    "for",
    "from",
    "has",
    "have",
    "in",
    "into",
    "is",
    "it",
    "its",
    "just",
    "more",
    "news",
    "now",
    "of",
    "on",
    "or",
    "our",
    "s",
    "say",
    "says",
    "so",
    "that",
    "the",
    "their",
    "them",
    "they",
    "this",
    "to",
    "today",
    "up",
    "was",
    "we",
    "were",
    "what",
    "when",
    "with",
    "you",
}
